// <auto-generated />
using System;
using DataImport.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataImport.Migrations
{
    [DbContext(typeof(SanctionsDbContext))]
    partial class SanctionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataImport.Models.DataImportLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Inserted")
                        .HasColumnType("int");

                    b.Property<int>("Parsed")
                        .HasColumnType("int");

                    b.Property<DateTime>("RanAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit");

                    b.Property<int>("Unchanged")
                        .HasColumnType("int");

                    b.Property<int>("Updated")
                        .HasColumnType("int");

                    b.Property<bool>("WasDownloaded")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RanAtUtc");

                    b.HasIndex("Succeeded", "RanAtUtc");

                    b.ToTable("DataImportLogs");
                });

            modelBuilder.Entity("DataImport.Models.SanctionDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecordUniqueId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("XmlRecord")
                        .IsRequired()
                        .HasColumnType("xml");

                    b.HasKey("Id");

                    b.HasIndex("RecordUniqueId")
                        .IsUnique();

                    b.ToTable("SanctionDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
